name: Chengwei's Words
author: Chengwei Yang
url: http://example.org
description: "{hello world}"
markdown: redcarpet
timezone: Asia/Chongqing

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
